Versioning created files
**Purpose**

Address SPIND-129, namely by version-tagging dumps and mem-mapped files to perform compat checks when reloading them.

**Context**

Checks done both for:
 - serialization: So that loading dumps can do checks and handle compat
 - Mem-mapped file via a metadata entry, containing both boost and struct version. 

    - Struct mismatch is unrecoverable and leads to a runtime exception.
    - BOOST version mismatch raises a warning

From C++
```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Memory mapped file structs mismatch. Expected: 2, Given: 1
```

From python (exception gets converted)
```
>>> from spatial_index import MorphIndexBuilder
>>> MorphIndexBuilder.load_disk_mem_map("build/tests/rtree.mem")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/leite/dev/SpatialIndex/spatial_index/node_indexer.py", line 192, in load_disk_mem_map
    return MorphIndexMemDisk.open(filename)
RuntimeError: Memory mapped file structs mismatch. Expected: 2, Given: 1
```